### PR TITLE
Minor enhancements #910

### PR DESCRIPTION
**Pull request by zehawki**
A sundry list of minor updates are done on this branch:

1.  Upload button on Image and Background plugins were not showing the strings - neither normal nor error. This has been corrected.
2. Allow gifs and webp formats of image to be uploaded / shown
3. Actually show the image the user is trying to upload so that it looks more WYSIWYG
4. Various small text changes / UI tweaks / icon changes

@macrozone unfortunately I made a bit of a mistake - I did not follow the excepted commit message format (saw it only after I finished). Would this PR be acceptable?

### CODE REVIEW

**Comment by zehawki** [comment]
I really dont know why I'm getting repeated conflicts. I always start with the latest in master. Like this shows, the branch I'm on is upto date with master:

image

**Comment by macrozone** [comment]
sorry, we just released v2 on master, which has a translation feature by @rexebin ! that lead to some conflicts.

I advice to make smaller pull requests, each with 1 (atomic, independent) change/commit.  This way you get less conflicts, conflicts are easier to resolve and pull requests are easier to review!

**Comment by zehawki** [comment]
OK going to redo the branch and its updates and do new PRs

**Comment by zehawki** [comment]
I think I understand the mistake I was making. I need to pull latest from react-page to my forked version of react-page each time before I start making updates. The "merge master into branch" method that I'm using in Github desktop will (obviously) merge the master from the fork into the branch from the fork, NOT the master from react-page like I was thinking. 

https://github.com/react-page/react-page/pull/963

**Comment by zehawki** [comment]
Now I'm fully in sync with upstream and able to see these conflicts on my local. Finally.

**Pull request closed without merging**
