### PR TITLE
Don't use target es6 in es transpile to support IE11

### PR DESCRIPTION
**Pull request by DouglasGabr**
## Proposed changes

ES target was transpiling with es6 features (like `const` and `=>`). This PR keeps the `import`s and `export`s, but transpile to es5 code (`var` and `function`)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by fernandobandeira** [comment]
cool, this should fix some IE issues we were having with the latest versions

**Comment by macrozone** [comment]
thanks guys! and sorry for beeing overly agressive with new features and changes.

Did you check if code-splitting still works? (should so).

**Comment by DouglasGabr** [comment]
@macrozone Yes, it is

**Comment by fernandobandeira** [comment]
@macrozone also don't worry, keep pushing man, we'll give the package some love too soon enough =P

**Comment by macrozone** [comment]
@fernandobandeira  :-D

as you are already here, checkout https://github.com/react-page/react-page/pull/744

see the examples for how this can be used

**Comment by macrozone** [comment]
@DouglasGabr did it fix the ie11 compatibility for you? i  still see syntax error in ie11, but i have to check whether i actually included your PR in master as i remember

**Pull request merged**
