### PR TITLE
fix(inline): fix inline layout

### PR DESCRIPTION
**Pull request by avoskresensky**
## Proposed changes

Revert to using display:block type of layout in case of inline cells.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Closing issues

#918

### CODE REVIEW

**Comment by avoskresensky** [comment]
@macrozone, this should take care of inline cell layout problems.

**Comment by macrozone** [comment]
thx!

**Pull request merged**
