### PR TITLE
PR for #910

### PR DESCRIPTION
**Pull request by zehawki**
Minor word smithing and UI tweaks

### CODE REVIEW

**Comment by zehawki** [comment]
@macrozone please check this. Like you mentioned, now I'm breaking it down into smaller updates.

**Comment by zehawki** [comment]
This is so random. Why will build fail on things like this:
image

**Comment by macrozone** [comment]
> This is so random. Why will build fail on things like this:
> image

please make sure you format on save. It should run prettier on it.

**Comment by macrozone** [comment]
approved, but you need to fix the formatting

**Comment by zehawki** [comment]
All the tabs are now slightly redesigned:

image

image

image

**Comment by zehawki** [comment]
Wow, released already!

**Pull request merged**
