### PR TITLE
Refactors

### PR DESCRIPTION
**Pull request by macrozone**

### CODE REVIEW

**Comment by macrozone** [comment]
@rexebin would you mind reviewing this? It will lead to slight conflicts with your i18n branch (will be straight forward to fix i think)

**Comment by rexebin** [comment]
Do you want me to merge this PR into the `uiTranslator` PR?

**Comment by macrozone** [comment]
> Do you want me to merge this PR into the `uiTranslator` PR?

or i merge it into beta and you can rebase on it

**Pull request merged**
